# Generated by Django 2.2.5 on 2020-02-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacollection',
            old_name='dat_age',
            new_name='data_age',
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='data_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
