# Generated by Django 2.2.5 on 2020-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='image',
            field=models.ImageField(blank=True, upload_to='data_photos'),
        ),
    ]
