# Generated by Django 2.2.5 on 2020-02-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollections', '0002_auto_20200204_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='user',
        ),
        migrations.AddField(
            model_name='datacollection',
            name='users',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
