# Generated by Django 2.2.5 on 2020-02-05 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_users', '0001_initial'),
        ('datacollections', '0003_auto_20200205_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='users',
        ),
        migrations.AddField(
            model_name='datacollection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datacollections', to='products_users.Products_User'),
        ),
    ]
