# Generated by Django 2.2.5 on 2020-02-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollections', '0004_auto_20200205_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='user',
        ),
    ]
