# Generated by Django 2.2.5 on 2020-02-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='updated',
        ),
    ]
